Answer.create([
  { content: '多い', explain: '留守番が苦手な犬ならこれを選ぶ', question_id: 1 },
  { content: '少ない', explain: '留守番が得意な犬ならこれを選ぶ', question_id: 1 },
  { content: '気になる', explain: '吠えることが多い犬ならこれを選ぶ', question_id: 2 },
  { content: '気にならない', explain: '吠えることが気にならない犬ならこれを選ぶ', question_id: 2 },
  { content: '2LDK未満', explain: '小型犬ならこれを選ぶ', question_id: 3 },
  { content: '2LDK以上', explain: '中型犬、大型犬ならこれを選ぶ', question_id: 3 },
  { content: 'いる', explain: '家庭に小さい子供がいるならこれを選ぶ', question_id: 4 },
  { content: 'いない', explain: '家庭に小さい子供がいないならこれを選ぶ', question_id: 4 },
  { content: '月に1万円未満', explain: 'トリミングに月に一万円未満かけるならこれを選ぶ', question_id: 5 },
  { content: '月に1万円以上', explain: 'トリミングに月に一万円以上かけるならこれを選ぶ', question_id: 5 },
  { content: 'はい', explain: 'アレルギーを起こしにくい犬種ならこちら', question_id: 6 },
  { content: 'いいえ', explain: 'アレルギーは特に気にしていないならこちら', question_id: 6 },
  { content: 'はい', explain: '運動量が多い犬ならこれを選ぶ', question_id: 7 },
  { content: 'いいえ', explain: '運動量が少ない犬ならこれを選ぶ', question_id: 7 },
  { content: '可愛い', explain: '見た目が可愛い系の犬ならこれを選ぶ', question_id: 8 },
  { content: 'かっこいい', explain: '見た目がかっこいい系の犬ならこれを選ぶ', question_id: 8 },
  { content: 'はい', explain: '暑がりな犬種ならこれを選ぶ', question_id: 9 },
  { content: 'いいえ', explain: '暑がりではない犬種ならこれを選ぶ', question_id: 9 },
  { content: 'はい', explain: '寒がりな犬種ならこれを選ぶ', question_id: 10 },
  { content: 'いいえ', explain: '寒がりではない犬種ならこれを選ぶ', question_id: 10 },
  { content: '人懐っこいタイプ', explain: '人懐っこいタイプならこちらを選ぶ', question_id: 11 },
  { content: '番犬タイプ', explain: '番犬タイプならこちらを選ぶ', question_id: 11 },
  { content: 'はい', explain: '初心者向けの犬種ではないならこちらを選ぶ', question_id: 12 },
  { content: 'いいえ', explain: '初心者向けの犬種ならこちらを選ぶ', question_id: 12 }
])

Question.create(content: '家にいることが多く、犬と触れ合う時間が多い？')
Question.create(content: '吠えることが多いと気になる？')
Question.create(content: '家の広さはどのくらい？')
Question.create(content: 'お家に小さいお子さんがいる？')
Question.create(content: 'トリミングにお金をかけることができる？')
Question.create(content: 'アレルギー体質？')
Question.create(content: 'ドッグスポーツなど激しめの運動をしたい？')
Question.create(content: '可愛い見た目orかっこいい見た目どちらが好き？')
Question.create(content: '暑がりですか？')
Question.create(content: '寒がりですか？')
Question.create(content: '人懐っこいタイプ or 番犬タイプ どちら派？')
Question.create(content: '犬を飼ったことがある？')

DogSizeType.create(name: '小型犬')
DogSizeType.create(name: '中型犬')
DogSizeType.create(name: '大型犬')
DogSizeType.create(name: 'その他')

DogCountry.create([
{name: 'アイスランド'},
{name: 'アイルランド'},
{name: 'アゼルバイジャン'},
{name: 'アルゼンチン'},
{name: 'アルバ'},
{name: 'アルバニア'},
{name: 'アンティグア・バーブーダ'},
{name: 'アンドラ'},
{name: 'イスラエル'},
{name: 'イタリア'},
{name: 'インド'},
{name: 'インドネシア'},
{name: 'ウガンダ'},
{name: 'ウクライナ'},
{name: 'ウルグアイ'},
{name: 'イギリス'},
{name: 'エクアドル'},
{name: 'エストニア'},
{name: 'オーストラリア'},
{name: 'オーストリア'},
{name: 'オマーン'},
{name: 'オランダ'},
{name: 'ガーナ'},
{name: 'ガーンジー'},
{name: 'カザフスタン'},
{name: 'カタール'},
{name: 'カナダ'},
{name: 'キプロス'},
{name: 'キュラソー'},
{name: 'ギリシャ'},
{name: 'クック'},
{name: 'グリーンランド'},
{name: 'グレナダ'},
{name: 'クロアチア'},
{name: 'ケニア'},
{name: 'コスタリカ'},
{name: 'コロンビア'},
{name: 'サウジアラビア'},
{name: 'サモア'},
{name: 'サンマリノ'},
{name: 'ジブラルタル'},
{name: 'ジャージー'},
{name: 'ジャマイカ'},
{name: 'シンガポール'},
{name: 'スイス'},
{name: 'スウェーデン'},
{name: 'スペイン'},
{name: 'スロバキア'},
{name: 'スロベニア'},
{name: 'セーシェル'},
{name: 'セントクリストファー・ネービス'},
{name: 'セントビンセント'},
{name: 'セントマーチン'},
{name: 'セントルシア'},
{name: 'タイ'},
{name: '大韓民国'},
{name: '台湾'},
{name: 'チェコ'},
{name: '中華人民共和国'},
{name: 'チリ'},
{name: 'デンマーク'},
{name: 'ドイツ'},
{name: 'ドミニカ'},
{name: 'トルコ'},
{name: 'ナイジェリア'},
{name: 'ニューカレドニア'},
{name: 'ニュージーランド'},
{name: 'ノルウェー'},
{name: 'パキスタン'},
{name: 'パナマ'},
{name: 'バヌアツ'},
{name: 'バルバドス'},
{name: 'ハンガリー'},
{name: 'フィンランド'},
{name: 'フェロー諸島'},
{name: 'ブラジル'},
{name: 'フランス'},
{name: 'ブルガリア'},
{name: 'ブルネイ'},
{name: 'ベリーズ'},
{name: 'ペルー'},
{name: 'ベルギー'},
{name: 'ポーランド'},
{name: 'ポルトガル'},
{name: '香港'},
{name: 'マカオ'},
{name: 'マルタ'},
{name: 'マレーシア'},
{name: 'マン島'},
{name: '南アフリカ共和国'},
{name: 'メキシコ'},
{name: 'モーリシャス'},
{name: 'モナコ'},
{name: 'モルディブ'},
{name: 'モルドバ'},
{name: 'モロッコ'},
{name: 'モンテネグロ'},
{name: 'モントセラト'},
{name: 'ヨルダン'},
{name: 'ラトビア'},
{name: 'リトアニア'},
{name: 'リヒテンシュタイン'},
{name: 'ルーマニア'},
{name: 'ルクセンブルク'},
{name: 'レバノン'},
{name: 'ロシア'},
{name: 'その他'}
])

DogAnswerRelationship.create([
  {dog_id: 1, answer_id: 1},
  {dog_id: 1, answer_id: 3},
  {dog_id: 1, answer_id: 5},
  {dog_id: 1, answer_id: 7},
  {dog_id: 1, answer_id: 8},
  {dog_id: 1, answer_id: 9},
  {dog_id: 1, answer_id: 11},
  {dog_id: 1, answer_id: 15},
  {dog_id: 1, answer_id: 18},
  {dog_id: 1, answer_id: 19},
  {dog_id: 1, answer_id: 21},
  {dog_id: 1, answer_id: 24},
  {dog_id: 2, answer_id: 2},
  {dog_id: 2, answer_id: 3},
  {dog_id: 2, answer_id: 5},
  {dog_id: 2, answer_id: 7},
  {dog_id: 2, answer_id: 8},
  {dog_id: 2, answer_id: 9},
  {dog_id: 2, answer_id: 12},
  {dog_id: 2, answer_id: 15},
  {dog_id: 2, answer_id: 17},
  {dog_id: 2, answer_id: 19},
  {dog_id: 2, answer_id: 21},
  {dog_id: 2, answer_id: 24},
  {dog_id: 3, answer_id: 2},
  {dog_id: 3, answer_id: 3},
  {dog_id: 3, answer_id: 5},
  {dog_id: 3, answer_id: 6},
  {dog_id: 3, answer_id: 7},
  {dog_id: 3, answer_id: 8},
  {dog_id: 3, answer_id: 9},
  {dog_id: 3, answer_id: 11},
  {dog_id: 3, answer_id: 15},
  {dog_id: 3, answer_id: 17},
  {dog_id: 3, answer_id: 20},
  {dog_id: 3, answer_id: 24},
  {dog_id: 4, answer_id: 1},
  {dog_id: 4, answer_id: 3},
  {dog_id: 4, answer_id: 6},
  {dog_id: 4, answer_id: 7},
  {dog_id: 4, answer_id: 8},
  {dog_id: 4, answer_id: 9},
  {dog_id: 4, answer_id: 11},
  {dog_id: 4, answer_id: 13},
  {dog_id: 4, answer_id: 16},
  {dog_id: 4, answer_id: 18},
  {dog_id: 4, answer_id: 19},
  {dog_id: 4, answer_id: 23},
  {dog_id: 5, answer_id: 1},
  {dog_id: 5, answer_id: 4},
  {dog_id: 5, answer_id: 6},
  {dog_id: 5, answer_id: 7},
  {dog_id: 5, answer_id: 9},
  {dog_id: 5, answer_id: 12},
  {dog_id: 5, answer_id: 13},
  {dog_id: 5, answer_id: 15},
  {dog_id: 5, answer_id: 17},
  {dog_id: 5, answer_id: 20},
  {dog_id: 5, answer_id: 22},
  {dog_id: 5, answer_id: 23},
  {dog_id: 6, answer_id: 2},
  {dog_id: 6, answer_id: 4},
  {dog_id: 6, answer_id: 6},
  {dog_id: 6, answer_id: 7},
  {dog_id: 6, answer_id: 9},
  {dog_id: 6, answer_id: 12},
  {dog_id: 6, answer_id: 13},
  {dog_id: 6, answer_id: 15},
  {dog_id: 6, answer_id: 18},
  {dog_id: 6, answer_id: 20},
  {dog_id: 6, answer_id: 22},
  {dog_id: 6, answer_id: 23},
  {dog_id: 7, answer_id: 2},
  {dog_id: 7, answer_id: 3},
  {dog_id: 7, answer_id: 6},
  {dog_id: 7, answer_id: 7},
  {dog_id: 7, answer_id: 9},
  {dog_id: 7, answer_id: 11},
  {dog_id: 7, answer_id: 14},
  {dog_id: 7, answer_id: 16},
  {dog_id: 7, answer_id: 17},
  {dog_id: 7, answer_id: 19},
  {dog_id: 7, answer_id: 21},
  {dog_id: 7, answer_id: 23},
  {dog_id: 8, answer_id: 1},
  {dog_id: 8, answer_id: 3},
  {dog_id: 8, answer_id: 6},
  {dog_id: 8, answer_id: 7},
  {dog_id: 8, answer_id: 10},
  {dog_id: 8, answer_id: 12},
  {dog_id: 8, answer_id: 13},
  {dog_id: 8, answer_id: 16},
  {dog_id: 8, answer_id: 17},
  {dog_id: 8, answer_id: 20},
  {dog_id: 8, answer_id: 21},
  {dog_id: 8, answer_id: 24},
  {dog_id: 9, answer_id: 2},
  {dog_id: 9, answer_id: 3},
  {dog_id: 9, answer_id: 6},
  {dog_id: 9, answer_id: 7},
  {dog_id: 9, answer_id: 8},
  {dog_id: 9, answer_id: 10},
  {dog_id: 9, answer_id: 13},
  {dog_id: 9, answer_id: 16},
  {dog_id: 9, answer_id: 17},
  {dog_id: 9, answer_id: 20},
  {dog_id: 9, answer_id: 22},
  {dog_id: 9, answer_id: 23},
  {dog_id: 10, answer_id: 2},
  {dog_id: 10, answer_id: 4},
  {dog_id: 10, answer_id: 6},
  {dog_id: 10, answer_id: 7},
  {dog_id: 10, answer_id: 9},
  {dog_id: 10, answer_id: 10},
  {dog_id: 10, answer_id: 12},
  {dog_id: 10, answer_id: 15},
  {dog_id: 10, answer_id: 17},
  {dog_id: 10, answer_id: 19},
  {dog_id: 10, answer_id: 21},
  {dog_id: 10, answer_id: 24}
])

Dog.create!(
  breed: 'トイプードル',
  height: '28cm以下',
  weight: '3kg',
  hair_length: 2,
  dog_size_type_id: 1,
  dog_image: 'toy_poodle.jpg',
  dog_country_id: 77,
  activity_level: 1,
  solitude_tolerance: 2,
  care_difficulty: 0,
  catchphrase: '不動の人気NO.1犬！初心者でも飼いやすい',
  features_sentence: 'トイ・プードルは大きさ別に4つに分類されるプードルの中でも非常に人気が高く、過去に何度も犬種別犬籍登録頭数1位を獲得しています。ふわふわでカールした被毛がぬいぐるみのようで、スクエア形のバランスのとれた体型が特徴的な犬種です。',
  personality_sentence: 'トイ・プードルは非常に賢く、運動能力が高く、好奇心旺盛であり、プードルの中でも最も賢いとされる犬種です。優等生的な性格で、家族や他の犬に対して愛情深く接し、他人にも上手に対応します。そのかわいらしい容姿とは裏腹に、知的で訓練がしやすく、活発で楽しいことが大好きです。社交的に育てられれば、見知らぬ人にも友好的ですが、訓練やコミュニケーションが不足すると神経質になり、吠える傾向があることに注意が必要です。',
  history_sentence: '歴史は15世紀のドイツの画家、アルブレヒト・デューラーの版画に登場し、小さなミニチュアプードルまたはトイプードルとして確認されています。',
  recommended_for_whom: '抜け毛や体臭が少なく、アレルギー体質の方にもおすすめです。また、移動が容易で電車などでのお出かけも楽しめ、遊ぶ時間がとれる飼い主に向いています。お手入れが億劫でない方にもおすすめの犬種です。',
  display_in_index: 1,
  youtube_url: 'OlL6eZ9TxGg'
)

Dog.create!([
  {
    breed: 'パグ',
    height: '25～28cm',
    weight: '6.3～8.1kg',
    hair_length: 0,
    dog_size_type_id: 1,
    dog_image: 'pug.png',
    dog_country_id: 59,
    activity_level: 1,
    solitude_tolerance: 2,
    care_difficulty: 0,
    catchphrase: '力強いが愛らしい、しわくちゃの笑顔と巻き巻きのしっぽ。その魅力、一瞬で心に刻まれる。',
    features_sentence: 'パグはラテン語で「パグナス（握りこぶし）」という名前の由来があり、その名の通り、ぺちゃっと潰れた鼻としわしわの顔からはまさに握りこぶしを連想させます。小型犬でありながらも、スクエアながっちり体型で筋肉質である特徴が際立ちます。短毛で滑らかな被毛がパグの個性を一層引き立てています。短い鼻が原因でいびきをかく子もいますが、その味わい深いかわいらしさに引き込まれ、一度飼えば次もパグを迎える人が多いのは納得です。',
    personality_sentence: '陽気でわんぱくな性格をしています。また小さな子どもとも相性抜群で、明るくのんびりしています。\n頑固で嫉妬深く独立心が高い一面もあります。しかし威厳をもって根気よく接せば理想のパートナーになります。\n攻撃性と警戒心が少ないため番犬向きではありませんが、無駄吠えも少ないです。',
    history_sentence: 'パグとブルドッグは起源や歴史が異なります。ブルドッグは13世紀のイギリス起源で、一方のパグは紀元前400年以前の中国に由来します。パグはチベットで仏教僧の愛玩犬として育まれ、次第に小型化されてできた犬だと言われています。その後オランダを経てヨーロッパで人気を博し、アメリカにも広まりました。',
    recommended_for_whom: '社交的な性格で、仲間で集まって楽しむ方にはぴったりです。\n初心者でも飼いやすく、愛嬌満点の容姿としぐさは家族にとってかけがえのないものになります。ただし、頑固な一面もあるため、早めのしつけが必要になります。\nまたパグは室内飼いが必須の犬種で、抜け毛が多く掃除をまめにする方が向いています。体調管理も重要で、暑さに弱いため環境管理や、顔のしわのスキンケアが必須になります。',
    display_in_index: 1,
    youtube_url: 'sJRpoA96ZXM'
  }
])

Dog.create!(
  breed: 'シー・ズー',
  height: '26.7cm以下',
  weight: '4.5～8.1kg',
  hair_length: 2,
  dog_size_type_id: 1,
  dog_image: 'shih_tzu.jpeg',
  dog_country_id: 59,
  activity_level: 0,
  solitude_tolerance: 1,
  care_difficulty: 0,
  catchphrase: 'おばあちゃんのように優しい見た目、大きいおめめで甘えてくる姿には悶絶♡',
  features_sentence: 'シーズーは鼻ぺちゃで垂れ耳、小柄ながらも体長がわずかに長く、幅広で頑丈な体型を持つ特徴的な犬種です。歩き方は落ち着いており、機嫌良さそうにわずかに体を揺らしながら歩きます。被毛は長い豊かなダブルコートで、様々な毛色があり、体全体を覆っているため気品あふれる雰囲気を漂わせます。鼻の周りの毛が四方に広がり、キクの花のような美しさを醸し出し、全体的な表情は愛嬌たっぷりです。',
  personality_sentence: "シーズーは遊び好きで活発な性格と穏やかで落ち着いた一面を持ちます。\n友好的で特に子供との付き合いが得意で、愛情深く神経質な傾向が少ないです。\n保守的でプライドが高いですが、飼い主に深い愛情を抱き、留番も得意です。\nただ、無視されると怒り出すこともあるあるので、かまって犬です。",
  history_sentence: "シー・ズーは中国の宮廷で飼育されたペキニーズと、チベットの寺院で愛されていたラサ・アプソの交配により、1600年ごろに誕生しました。\n頭部の被毛がライオンに似ている独特な外見から「獅子狗（シー・ズー・クゥ）」と呼ばれ、神聖な存在として崇められていました。\n1930年にイギリスに持ち込まれ、第二次世界大戦後の1960年代にアメリカで広まり、その後日本でも人気を博し、現代では世界中の人気者になりました。",
  recommended_for_whom: 'シー・ズーは小型犬に見られる興奮性や活発さは少なく、攻撃性も低いので、初めて犬を迎える方でも安心して飼える犬種です。子犬の時期に見られる「遊び噛み」も、ひどくなることはあまりありません。ただし、皮膚や耳、目、呼吸器などの病気にかかりやすい傾向があるため、健康ケアには気を配ってあげましょう。',
  display_in_index: 1,
  youtube_url: '0MAwZAaeZtk'
)

Dog.create!(
  breed: 'イタリアン・グレーハウンド',
  height: '32～38cm',
  weight: '3kg～5kg',
  hair_length: 0,
  dog_size_type_id: 1,
  dog_image: 'Italian_greyhound_.jpeg',
  dog_country_id: 10,
  activity_level: 2,
  solitude_tolerance: 2,
  care_difficulty: 0,
  catchphrase: 'ルネッサンスの王族も魅了された上品＆優雅なわんちゃん代表',
  features_sentence: 'イタリアングレーハウンドは最小のサイトハウンド犬種で、気品あふれる歩き方や優雅なスタイルが魅力です。耳の形は、前ではなく横に垂れる形が標準とされていますが、子犬の頃からずっと立ち耳の子も多くいます。\n走る時はグレーハウンド独特のスタイルで、バンビが軽やかに跳びはねているように両手両足を揃えて走ります。\nただし、骨が細いため、骨折には十分な注意が必要です。脚にかかる負担については、家庭で丁寧にケアしていただくことが重要です。',
  personality_sentence: '繊細で感受性が強く、攻撃的な性格というよりは穏やかで優しい性格をしています。\n活発でスタミナもあり走ることが好きであり、物覚えもいいため、トレーニングも難しくありません。\n飼い主との信頼関係は強く、温厚で愛情豊かであり子供や他のペットとも友好的に過ごしますが、見知らぬ人に対しては警戒心と臆病さが顕著にでます。社会性を養うために幼いころから人や犬との触れ合いが重要になります。',
  history_sentence: 'イタリアングレーハウンドの先祖は約6000年前の古代エジプトまで遡り、エジプトからギリシャを経て紀元前5世紀ごろにイタリアに至ったと考えられています。視力と俊足を生かした大型のグレイハウンドを小型に改良してきた結果、滑らかな短毛とスマートな体躯が特徴となり、ヨーロッパ諸国の王族や支配階級のコンパニオン・ドッグとして人気を博しました。また、異国の交易にも関わるなど多岐にわたる歴史を刻んでいます。',
  recommended_for_whom: 'イタリアングレーハウンドは短毛でお手入れが容易で、温厚で家族になじみやすい性格のため、初心者向けの犬種と言えます。\n遊び好きな一面もあり、安全な屋外での運動が重要になるので毎日約30分の散歩を2回程度する必要があります。\n骨が弱く寒さにも弱いという性質があり、また神経質な性格も持ち合わせています。適切な生活環境と体重管理に配慮することが必要になりますので、その点を配慮できる方におすすめな犬種といえます。',
  display_in_index: 1,
  youtube_url: 'OWvdF50vh5c'
)

Dog.create!(
  breed: 'ボーダー・コリー',
  height: '53cm',
  weight: '14～20kg',
  hair_length: 3,
  dog_size_type_id: 2,
  dog_image: 'border_collie.jpeg',
  dog_country_id: 16,
  activity_level: 2,
  solitude_tolerance: 2,
  care_difficulty: 2,
  catchphrase: '賢くてスポーティー！飼い主への想いが止まらない、ワンちゃん界NO.1の一途犬♥',
  features_sentence: 'ボーダー・コリーは均整が取れた滑らかなアウトラインとしっかりとした体つきを持ち、耐久力があります。被毛にはスムース（短くまっすぐな毛質）とラフ（長く粗い毛質）の2種類があり、30種以上の毛色が認められます。フレーズと呼ばれる白い毛が特徴で、「面ずれ」や「パンダ」といった模様を形成し、個々のボーダー・コリーに異なる表情を与えています。また、耳の形も様々で、立ち耳、垂れ耳、片方だけ垂れているなど、ボーダー・コリーは多様な個性を持っているのも魅力の一つでもあります。',
  personality_sentence: "ボーダー・コリーは非常に頭が良く、活発で作業意欲が強い性格です。洞察力があり、作業中には状況を判断して主導できます。\n家族には愛情深く忠実で、知らない人や犬にはあまり関心を示さず、人間との作業を好む傾向があります。\n思慮深く、飼い主に対して忠実で、頭の良さはトップクラスです。\n無邪気で人なつこく、優しく明るく、我慢強い性格を持ち、好奇心旺盛な家庭犬です。\n飼い主の指示をよく理解し、高い知能を活かして臨機応変な問題解決能力を発揮します。",
  history_sentence: "ボーダー・コリーの名前の由来は、イングランドとスコットランドの国境である「ボーダー」の地域出身であることからきています。この犬種はビアデッド・コリーやスコッチ・コリーと親戚関係にあり、北方地方のトナカイの牧畜犬の血も混ざっています。18世紀には既に牧羊犬として優れた働きをし、牧場主の信頼を得て広く飼われるようになりました。その牧羊能力はオーストラリアやニュージーランドにも広まり、羊の群れを巧みに操る優れた技術が発展しました。",
  recommended_for_whom: '無視をされると、怒り出すことも少なくありません。いつでもかまってあげることができて、しかも、しっかりとしつけられる人に向いているわんちゃんでしょう。\n遊ぶことが大好きなわんちゃんなのでアウトドア好きな人に向いています',
  display_in_index: 1,
  youtube_url: '5k1Ifbzav2k'
)

Dog.create!(
  breed: 'ビーグル',
  height: '33～40cm',
  weight: '9～16kg',
  hair_length: 0,
  dog_size_type_id: 2,
  dog_image: 'beagle.jpeg',
  dog_country_id: 16,
  activity_level: 1,
  solitude_tolerance: 1,
  care_difficulty: 1,
  catchphrase: 'エネルギッシュでタフ。実は、スヌーピーのモデルとなったわんちゃん！',
  features_sentence: 'ビーグルは短毛で垂れ耳、中ぐらいの長さの口先を持ち、骨太でしっかりした体格の中型犬です。最大の特徴は大きく太くよく通る吠え声で、特に大きな垂れ耳が顕著です。この特徴的な耳とピンと立った太い尾が、ビーグルのトレードマークで、これらがキャラクター・スヌーピーのモデルになったことでも知られています。ビーグルの被毛はハウンドカラーと呼ばれ、胸と腹部、四肢が白で頭部や背中に色が出ます。尻尾の先は白であることが必須で、体色はレバー以外であれば許容されます。スヌーピーのような背中と耳だけに黒い班の入ったビーグルは珍しい部類に属します。',
  personality_sentence: 'ビーグルはエネルギッシュで元気いっぱい、独立心が強くて飼い主と遊ぶことも大好きな性格です。シンプルで素直、人間が褒めてくれることやちょっとしたご褒美が大好きです。家族とは仲良く楽しい時間を過ごし、元気でタフな体が魅力のポイント。でも、ちょっとやんちゃでおてんばな一面もあるので、しっかりとしたしつけが必要です。協調性・社会性が高く、他の犬ともフレンドリーに接することができ、新しい友達と仲良くなることが得意です。',
  history_sentence: 'ビーグルは、古代ギリシャでウサギ狩りに使われた猟犬の子孫で、紀元前からその存在が確認されています。初めての記録は1475年にさかのぼり、16世紀にはイギリスで猟犬として重要な役割を果たしていました。この犬種はギリシャからローマ帝国を経て広く欧州に広がり、ヘンリー7世からエリザベス一世の時代にかけて品種改良が行われ、19世紀になると今日見られるスタイルが確立されました。',
  recommended_for_whom: '次の4犬種はブラッシングやトリミングといったお手入れの時間や手間、費用面で飼いやすいといわれています。活発で好奇心旺盛な性格のため、とくに子犬のころにはいたずらをしてしまうことがあります。しかし攻撃的であったり、神経質であったりというわけではないので、しつけや成長により行動は変わっていくでしょう。\n遊び好きな子が多いので、たくさん遊びを通じてスキンシップをとってあげるといい関係性を築けます。',
  display_in_index: 1,
  youtube_url: 'Z9Uv42AFbi4'
)

Dog.create!(
  breed: 'ブルドッグ',
  height: '31～40cm',
  weight: '18～25kg',
  hair_length: 0,
  dog_size_type_id: 2,
  dog_image: 'bulldog.jpeg',
  dog_country_id: 16,
  activity_level: 0,
  solitude_tolerance: 2,
  care_difficulty: 2,
  catchphrase: 'たくましい外見に物事に動じないクールなやつ！マッシブなハートの愛され力持ち',
  features_sentence: 'ブルドッグはがっしりとした肉づきで頑丈な体つきを持っています。短い足があり、低い重心で安定感があり、幅広い肩幅と大きな頭部を特徴としています。被毛はスムースで、独特の形をした耳や極めて短い口元が際立っています。マッチョであり、離れた目と、上唇があごの上に垂れ下がっている様子からは、荒々しく怖そうな印象を受けますが、時折見せる愛くるしい表情に心をつかまれます。ブルドッグの最大の特徴である、独特の鼻は、闘犬時代の名残りとして、斜め上を向いています。',
  personality_sentence: "おっとりとした性格で、頑固さと物事に動じない精神的な強さが備わっていますが、一方で頑固で一度決めたら譲らない一面もあります。\n飼い主に対しては忠誠心が高く甘えん坊で、陽気な振る舞いと容姿のギャップの可愛さに見るものをほっこりさせます。\n知らない人には愛想よく振る舞うことは少ないが、警戒心は少ないため、番犬向きではありません。\n性別の違いでは、オスは勇敢で活発な傾向があり、メスはおっとりとした性格が一般的です。",
  history_sentence: "ブルドッグはもともと闘犬として古くから存在し、13世紀のイギリスではブルバイティング（雄牛との戦い）で人気を博し、品種改良が進みました。競技が法で禁じられた後も愛好者たちの努力により生き残り、ドッグショーで改良されて再び人気を得ました。日本でも調味料のキャラクターとして知名度があり、その個性的なキャラクターが重宝されています。正式名称は「イングリッシュ・ブルドッグ」で、イギリスが原産で国犬でもあります。13〜18世紀には牛と犬の戦いが娯楽として広く行われ、禁止後に穏やかな性格の個体が作られました。",
  recommended_for_whom: 'ブルドッグは犬の世話が大好きで、健康面にしっかり向き合える人に向いています。\n毎日のシワのお手入れや特有の健康管理が必要なため、時間と愛情をかけることが求められます。医療費がかかりやすいので経済的な余裕も重要な判断基準です。\n短頭種独特のトラブルに対処する経験が必要で、初心者向きではありません。\n成犬は寝そべっており、運動嫌いな傾向があるが、肥満予防のためには毎日の散歩が必要です。散歩のポイントを押さえ、時間と労力をかけられる飼い主さんに適しています。',
  display_in_index: 1,
  youtube_url: '3pu25EpI-XQ'
)

Dog.create!(
  breed: 'ゴールデン・レトリバー',
  height: '51～61cm',
  weight: '25～34kg',
  hair_length: 1,
  dog_size_type_id: 3,
  dog_image: 'golden_retriever.jpeg',
  dog_country_id: 16,
  activity_level: 2,
  solitude_tolerance: 2,
  care_difficulty: 1,
  catchphrase: '時には盲導犬、時には警察犬。その優しい見た目と抜群の学習能力で、家庭でもお仕事でも輝きを放つ',
  features_sentence: '大型犬のバランスの取れた体つきで、たくましい外見と垂れ耳、暗褐色のアーモンド型の目の愛くるしさが特徴です。\n被毛は美しい金色の毛並みのダブルコートで、硬めのオーバーコートと柔らかめのアンダーコートの2重構造を持ち、一年を通して抜け毛が比較的多いです。\nまた吠え声は深く太く、多方面での活躍が見込まれる盲導犬や聴導犬、災害救助犬、警察犬、麻薬捜査犬などでも重宝されています。',
  personality_sentence: '大変賢く穏やかで、家族に対して愛情深く、活発な遊び好きです。\n寛容で神経質な行動が少なく攻撃性も低いため、他の犬や子供に対しても安心して接することができます。\n高い学習能力があり、運動能力も高いためアウトドアやドッグスポーツが適しています。',
  history_sentence: 'ゴールデン・レトリーバーは1800年代にイギリスで誕生し、ツイード・ウォーター・スパニエルやニューファンドランド、アイリッシュ・セターなどの交配を経て現在の形に進化しました。水陸両用の優れた狩猟犬としてイギリスで人気を博し、1890年代にはアメリカにも輸入されました。1920年代までは主に実用犬として使われ、ドッグショーにおいて注目を浴びるのはその後のことでした。',
  recommended_for_whom: 'ゴールデン・レトリーバーは活発で好奇心旺盛、毎日の運動や遊びが必要なため、アクティブな飼い主におすすめです。\n性格面では穏やかで友好的なため初心者にも向いていますが、体力に対する理解と時間が必要です。\nまた、子どもがいる家庭にも適しており、小さな犬や幼い子にも優しく接することができます。\n社会性を育て、家族との円満な共生を楽しむには、穏やかで友好的な性格が魅力的です。',
  display_in_index: 1,
  youtube_url: '66JKSjlDEfc'
)

Dog.create!(
  breed: 'グレート・ピレニーズ',
  height: '65～80cm',
  weight: '50kg～60kg',
  hair_length: 1,
  dog_size_type_id: 3,
  dog_image: 'great_pyrenees.jpeg',
  dog_country_id: 77,
  activity_level: 1,
  solitude_tolerance: 2,
  care_difficulty: 2,
  catchphrase: '大人気漫画『SPY×FAMILY』でも登場、愛らしくも頼りがいのある大きなぬいぐるみ',
  features_sentence: '巨体でありながら動きが意外にも素早く、優雅で迫力満点の大型犬。がっちりとした骨格に大きな頭、小さくやや斜めのアーモンド型の目、垂れ耳、そしてダブルコートの厚い毛が特徴的です。\n子犬の時はふんわりとした毛とまんまるな体つきがまるでふわふわの雪だるまのように愛くるしく、見ている人を自然と笑顔にさせる存在です。',
  personality_sentence: 'グレートピレニーズは大きな優雅な姿とおっとりした性格が特徴ですが、警戒心が強く、洞察力と自己判断力も備えています。番犬や牧羊犬としての歴史的な背景から独立心が強く、攻撃性を持つことも。家庭犬としてはおおらかで穏やかな性格が求められ、子犬時から従順で落ち着いた性格を育むことが重要です。群れに対する仲間意識が強く、信頼関係が築ければ家族に対しても愛情深く接する傾向がありますが、特にオスは縄張り意識が強くトラブルになる可能性があるため、注意が必要です。',
  history_sentence: 'フランスとスペインの国境に広がるピレネー山地で古くから牧羊犬や護衛犬として活躍してきました。その祖先はアジアから連れてきた遊牧民の犬で、マレンマ・シープドッグとチベタン・マスティフの影響を受けています。17世紀にはフランス宮廷の番犬として知られ、王室や貴族に愛されました。時代の変遷とともに人気が下がりかけましたが、愛好者によって改良繁殖が行われ、家庭犬としての性格や白い毛色が強化されました。アメリカにも輸入され、今では穏やかで信頼できるペットとして広く親しまれています。',
  recommended_for_whom: 'グレート・ピレニーズは体力があり、引っ張りや押し倒しのある大型犬なので、体力に自信のある人や運動時間を確保できる飼い主に向いています。大きな庭があり、十分な散歩を提供できる環境が必要で、金銭的負担も考慮すべきです。加えて、大型犬の特性を理解し、適切なしつけやケアを提供できる経験豊富な飼い主が向いています。初心者には難易度が高いため、サポートを受けながら飼育することが重要です。',
  display_in_index: 1,
  youtube_url: 'HDVFsFwm2Gc'
)

Dog.create!(
  breed: 'サモエド',
  height: '54cm～60cm',
  weight: '16kg～30kg',
  hair_length: 2,
  dog_size_type_id: 3,
  dog_image: 'samoyed.jpeg',
  dog_country_id: 106,
  activity_level: 2,
  solitude_tolerance: 2,
  care_difficulty: 2,
  catchphrase: '人々に癒しと幸福感をもたらすサモエドスマイルはほほえみの奇跡',
  features_sentence: 'サモエドは全身を覆う白いふわふわの被毛が特徴で、アーモンド形の黒い目と上向きに切り込んだ口角から「サモエド・スマイル」と呼ばれる可愛らしい表情が魅力です。その雪のような被毛は寒冷な地域に適応し、ボリュームがあり大きな体をさらに引き立てます。筋肉質な体つきは労働に優れており、高い吠え声や得意な遠吠えが特徴です。',
  personality_sentence: '優しく温和で辛抱強く、他人や他の犬にもフレンドリーな性格です。遊び好きでボール遊びやひっぱりっこが大好きで、子どもの遊び相手としても理想的です。社交的で人見知りをせず番犬向きではない一方で、頑固な一面もあるため、子犬の頃からしっかりとしたしつけが必要になります。飼い主に寄り添う甘えん坊ですが、神経質な一面もあり時には防衛的に吠えることもあります。',
  history_sentence: 'サモエドはロシア北部とシベリアのサモエド族が猟やそり引きに使っていた犬種で、小屋で人と共に生活し、豊かな被毛が寒冷地での防寒となっていました。イギリス人によって改良され、1909年に初めてのスタンダードが確立。別名「シベリアン・スピッツ」とも呼ばれ、日本スピッツの祖先とされています。',
  recommended_for_whom: '豊かなダブルコートは換毛期に抜け毛が多いため、ブラッシングやシャンプーなどの手入れをしっかりと行える人に向いています。力強い体力を持つため初心者向けではなく、トレーニングやコントロールが必要になります。寒冷地方原産なので夏のケアが必要で手間と時間がかかりますが、優しさと温厚さを持つ飼い主にとっては理想的なパートナーです。',
  display_in_index: 1,
  youtube_url: '8urBdlEBIGM'
)

Dog.create([
  {breed:'アイリッシュウルフハウンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'アイリッシュセッター', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'秋田犬', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'アフガンハウンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'アメリカンコッカースパニエル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'アメリカンスタッフォードシャーテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'アメリカンピットブルテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'アラスカンマラミュート', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'イングリッシュコッカースパニエル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'イングリッシュスプリンガースパニエル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'イングリッシュセッター', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'イングリッシュポインター', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ウィペット', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ウェルシュ・コーギー・ペンブローク', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ウェルシュ・コーギー・カーディガン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ウェルシュテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ウエストハイランドホワイトテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'エアデールテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'オーストラリアンケルピー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'オールドイングリッシュシープドッグ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'カーリーコーテッドレトリバー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'甲斐犬', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'カニンヘンダックスフンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'キースホンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'紀州犬', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'キャバリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'グレートデン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ケアーンテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ケリーブルーテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'コーイケルホンディエ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'コモンドール', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'サルーキ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'シーリハムテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'シェットランドシープドッグ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'四国犬', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'柴犬', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'シベリアンハスキー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'シャーペイ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ジャーマン・シェパード・ドッグ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ジャーマンピンシャー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ジャイアントシュナウザー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ジャックラッセルテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'スキッパーキ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'スコティッシュテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'スタッフォードシャーブルテリア(スタッフィー)', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'スタンダードシュナウザー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'スタンダードダックスフンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'スタンダードプードル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'スムースコートチワワ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'セントバーナード', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'タイニープードル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ダックスフンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ダルメシアン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'チェサピークベイレトリバー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'チベタンスパニエル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'チャイニーズ・クレステッド・ドッグ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'チャウチャウ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'チワワ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'狆(チン)', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ティーカッププードル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'トイマンチェスターテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'土佐犬', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ドーベルマン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'日本スピッツ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ニューファンドランド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ノーフォークテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ノーリッチテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'バーニーズ・マウンテン・ドッグ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'バセットハウンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'バセンジー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'パピヨン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ビアデッドコリー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ビションフリーゼ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'フラットコーテッドレトリバー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'フレンチブルドッグ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ブービエ・デ・フランダース', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ブリアード', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ブリタニースパニエル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ブリュッセルグリフォン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'プードル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'プチバセットグリフォンバンデーン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'プチブラバンソン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ベルジアングリフォン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ペキニーズ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'北海道犬', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ボクサー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ボストンテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ボルゾイ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ボロニーズ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ポメラニアン', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ポリッシュローランドシープドッグ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'豆柴', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'マルチーズ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'マンチェスターテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ミディアムプードル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ミニチュアシュナウザー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ミニチュアダックスフンド', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ミニチュアピンシャー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ミニチュアブルテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ミニチュアプードル', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ヨークシャーテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ラサアプソ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ラフコリー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ラブラドールレトリバー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'レークランドテリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'レオンベルガー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ロットワイラー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ロングコートチワワ', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ワイアーフォックステリア', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0},
  {breed:'ワイマラナー', dog_size_type_id: 4, dog_country_id: 107, display_in_index: 0}
])



